-- ALCOHOL TABLE TEST DATA
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (21, '별산막걸리', '탁주', 27000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (22, '부자진 오미자', '증류주', 45000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (23, '청포도와인 광야', '와인', 19000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (24, '시나브로 에뚜왈 화이트', '와인', 27000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (25, '선호 생막걸리', '탁주', 29900);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (26, '담화탁주', '탁주', 33000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (27, '고구마 증류소주', '증류주', 35200);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (28, '루드베리', '와인', 27000);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (29, '수삼23', '증류주', 11400);
INSERT INTO MINIP.ALCOHOL (AL_ID, AL_NAME, AL_TYPE, AL_PRICE) VALUES (30, '소곡화주', '증류주', 16200);
commit;

-- MEMBERS TABLE TEST DATA
INSERT INTO MINIP.MEMBERS (ID_EMAIL, PWD, NAME, BIRTH, PHONE) VALUES ('seonho@gmail.com', 'password1234', '김선호', '19860508', '010-1134-2587');
INSERT INTO MINIP.MEMBERS (ID_EMAIL, PWD, NAME, BIRTH, PHONE) VALUES ('jongmin@gmail.com', 'password1234', '김종민', '19790924', '010-8877-9874');
INSERT INTO MINIP.MEMBERS (ID_EMAIL, PWD, NAME, BIRTH, PHONE) VALUES ('dindin@gmail.com', 'password1234', '딘딘', '19911120', '010-9988-7744');
commit;

-- BASKET TABLE TEST DATA
INSERT INTO MINIP.BASKET (ID_EMAIL, AL_ID, CNT_NUMBER, ORDER_NUM) VALUES ('seonho@gmail.com', 24, 1, 0);
INSERT INTO MINIP.BASKET (ID_EMAIL, AL_ID, CNT_NUMBER, ORDER_NUM) VALUES ('seonho@gmail.com', 28, 1, 0);
INSERT INTO MINIP.BASKET (ID_EMAIL, AL_ID, CNT_NUMBER, ORDER_NUM) VALUES ('seonho@gmail.com', 26, 1, 43);
INSERT INTO MINIP.BASKET (ID_EMAIL, AL_ID, CNT_NUMBER, ORDER_NUM) VALUES ('seonho@gmail.com', 23, 1, 43);
commit;


-- ORDERS TABLE TEST DATA
INSERT INTO MINIP.ORDERS (ORDER_NUM, ID_EMAIL, ORGDATE, ADDRESS) VALUES (43, 'seonho@gmail.com', TO_DATE('2021-05-06 16:48:37', 'YYYY-MM-DD HH24:MI:SS'), '서울시 마포구 신수동');
commit;

-- REQBOARD TABLE TEST DATA
INSERT INTO MINIP.REQBOARD (REQ_NUM, TITLE, CONTENT, W_DATE, ID_EMAIL) VALUES (23, '루드베리 드셔보신 분', '이거 맛있어요?', TO_DATE('2021-05-06 16:52:04', 'YYYY-MM-DD HH24:MI:SS'), 'seonho@gmail.com');
INSERT INTO MINIP.REQBOARD (REQ_NUM, TITLE, CONTENT, W_DATE, ID_EMAIL) VALUES (21, '주문문의', '주문이 완료가 된건가요? 확인부탁드려요! 주문번호 43이에요!', TO_DATE('2021-05-06 16:49:37', 'YYYY-MM-DD HH24:MI:SS'), 'seonho@gmail.com');
INSERT INTO MINIP.REQBOARD (REQ_NUM, TITLE, CONTENT, W_DATE, ID_EMAIL) VALUES (22, '배송문의', '주문하면 보통 배송 얼마나 걸리나요? ', TO_DATE('2021-05-06 16:50:29', 'YYYY-MM-DD HH24:MI:SS'), 'jongmin@gmail.com');
commit;

-- COMMENTS TABLE TEST DATA
INSERT INTO MINIP.COMMENTS (COM_NUM, CONTENT, COM_DATE, ID_EMAIL, REQ_NUM) VALUES (17, '이거 생각보다 맛있어요 진짜 맛있으니까 꼭 시켜서 두세요 두번드세요', TO_DATE('2021-05-06 16:53:06', 'YYYY-MM-DD HH24:MI:SS'), 'dindin@gmail.com', 23);
commit;