-- MEMBERS TABLE 
create table MEMBERS
(
	ID_EMAIL VARCHAR2(20) not null
		primary key,
	PWD VARCHAR2(20) not null,
	NAME VARCHAR2(10) not null,
	BIRTH VARCHAR2(8) not null,
	PHONE VARCHAR2(13) not null
)
/

-- ALCOHOL TABLE
create table ALCOHOL
(
	AL_ID NUMBER not null
		primary key,
	AL_NAME VARCHAR2(1000) not null,
	AL_TYPE VARCHAR2(20) not null,
	AL_PRICE NUMBER not null
)
/

create index ALCOHOL_TYPE
	on ALCOHOL (AL_TYPE)
/

-- BASKET TABLE
create table BASKET
(
	BASKET_NUM NUMBER not null
		primary key,
	ID_EMAIL VARCHAR2(20) not null
		references MEMBERS,
	AL_ID NUMBER not null
		references ALCOHOL,
	CNT_NUMBER NUMBER not null,
	ORDER_NUM NUMBER default 0
)
/

-- REQBOARD TABLE
create table REQBOARD
(
	REQ_NUM NUMBER not null
		primary key,
	TITLE VARCHAR2(500) not null,
	CONTENT VARCHAR2(4000) not null,
	W_DATE DATE default SYSDATE not null,
	ID_EMAIL VARCHAR2(20) not null
		references MEMBERS
)
/

-- COMMENTS TABLE
create table COMMENTS
(
	COM_NUM NUMBER not null
		primary key,
	CONTENT VARCHAR2(4000) not null,
	COM_DATE DATE default SYSDATE not null,
	ID_EMAIL VARCHAR2(20) not null
		references MEMBERS,
	REQ_NUM NUMBER not null
		references REQBOARD
)
/

-- ORDERS TABLE
create table ORDERS
(
	ORDER_NUM NUMBER not null
		primary key,
	ID_EMAIL VARCHAR2(20) not null
		references MEMBERS,
	ORGDATE DATE default SYSDATE not null,
	ADDRESS VARCHAR2(700) not null
)
/

-- SEQUENCE ALL
CREATE SEQUENCE SEQ_COM
MINVALUE 1
MAXVALUE 99999999999
INCREMENT BY 1
START WITH 00001 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEQ_AL
MINVALUE 1
MAXVALUE 99999999999
INCREMENT BY 1
START WITH 00001 CACHE 20 NOORDER NOCYCLE;


CREATE SEQUENCE SEQ_BASK
MINVALUE 1
MAXVALUE 99999999999
INCREMENT BY 1
START WITH 00001 CACHE 20 NOORDER NOCYCLE;


CREATE SEQUENCE SEQ_OR
MINVALUE 1
MAXVALUE 99999999999
INCREMENT BY 1
START WITH 00001 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEQ_REQ
MINVALUE 1
MAXVALUE 99999999999
INCREMENT BY 1
START WITH 00001 CACHE 20 NOORDER NOCYCLE;
